[package]
org = "ballerina"
name = "editools"
version = "1.0.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name= "edi"
version= "1.0.0"
repository= "local"